### ISSUE TITLE
get package Failed 

### ISSUE THREAD

**Issue by gao114882** [StackExchange/wmi#60]
go get github.com/StackExchange/wmi   failed, the error is: 

go: github.com/StackExchange/wmi upgrade => v0.0.0-20210708210415-b284ef6ab838
go get: github.com/StackExchange/wmi@v0.0.0-20210708210415-b284ef6ab838: parsing go.mod:
	module declares its path as: wmi
	        but was required as: github.com/StackExchange/wmi

can you help me fix up this ?

**Comment by lazyman01** [comment]
yes me too, how to fix this

**Comment by gao114882** [comment]
go.mod  add this 
replace github.com/StackExchange/wmi v0.0.0-20210708210415-b284ef6ab838 => github.com/StackExchange/wmi 1.1.0

**Comment by tlimoncelli** [comment]
I'm not very good at git but I think I fixed this. Please verify.

**Comment by gao114882** [comment]
> I'm not very good at git but I think I fixed this. Please verify.

I tried , Unfortunately， this error still exists.  this error occurs at today, you can check what's changed today。
